### PR TITLE
Ensure valid access token before each Azure service call

### LINKED ISSUE #218: Azure commands should automatically re-authenticate if necessary
**Describe the bug**
Currently, only the `%azure.connect` magic command attempts to perform authentication and retrieve a token for use with Azure Quantum API calls. If that token expires, other `%azure.*` calls will fail until another call to `%azure.connect` is made.

**To Reproduce**
1. Connect successfully to an Azure Quantum workspace using `%azure.connect`.
2. Wait until the token expires (likely >1 hour).
3. Make another API call, e.g., `%azure.jobs`.
4. Command fails. Error message doesn't indicate what exactly went wrong. It just says that no jobs were retrieved.

**Expected behavior**
Every service call should attempt to re-authenticate automatically. In most cases this will succeed silently, and the user will never need to know about it.

If re-authentication fails, then an error message should be displayed that indicates specifically that there was an authentication failure.

**Additional context**
For reference, here is the existing code snippet inside `AzureClient.ConnectAsync()` that performs the authentication:

https://github.com/microsoft/iqsharp/blob/11d393d19854282502d82bab3c4335827b73329b/src/AzureClient/AzureClient.cs#L76-L92

### PR DESCRIPTION
**Pull request by rmshaffer**
Fixes #218 by running the MSAL authentication code, which is triggered in this code by calling `RefreshConnectionAsync()`, before every Azure service call. This code ensures that the current access token is not expired and fetches a new one if necessary.

### CODE REVIEW

File: src/AzureClient/AzureClient.cs [hunk 1]
```diff
@@ -72,6 +82,37 @@ public class AzureClient : IAzureClient
...
+        {
+            var connectionResult = await ConnectToWorkspaceAsync(channel, subscriptionId, resourceGroupName, workspaceName, refreshCredentials);
+            if (connectionResult.Status != ExecuteStatus.Ok)
+            {
+                return connectionResult;
+            }
+
+            if (ActiveWorkspace == null)
+            {
+                return AzureClientError.WorkspaceNotFound.ToExecutionResult();
```
Comment (ricardo-espinoza) [inline src/AzureClient/AzureClient.cs:94]: Is this something that we would like to log as an error?

Comment (rmshaffer) [reply src/AzureClient/AzureClient.cs:94]: Returning an error here causes the magic command `%azure.connect` to return an error status, which will be logged and communicated back to the user.

(This particular case should never really happen, since the current implementation of `ConnectToWorkspaceAsync` should have always set `ActiveWorkspace` if it returns `ExecuteStatus.Ok`, but it seems necessary to keep this here to convince the compiler that `ActiveWorkspace` truly is not `null` when using it below.)
